name: CI Main

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run CI
        run: bun run ci

      - name: Prepare .npmrc for publishing
        run: |
          echo "@secretkeylabs:registry=https://registry.npmjs.org/" > .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_PACKAGE_REGISTRY_TOKEN }}

      - name: Publish to NPM package registry
        # https://github.com/oven-sh/bun/issues/1976
        run: bunx npm@latest publish --access=public --tag=latest
